version: "3.4"
volumes:
  ssh-data:
    driver: local

services:
  nginx:
    build:
      context: nginx-hello/
      dockerfile: Dockerfile
    depends_on:
      - "webhook"
    environment:
      - SSH_HOSTUSER=${USER}
      - WEBHOOK_CONTAINER_NAME=webhook
      - WEBHOOK_URI=none
      - WAIT_FOR_WEBHOOK=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 8080:80

  webhook:
    image: avinson/localhost-dot-run
    container_name: webhook
    restart: unless-stopped
    stdin_open: true
    tty: true
    environment:
      - SSH_HOSTUSER=${USER}
      - SSH_TUNNEL_HOST=nginx
      - SSH_TUNNEL_LOCAL=8080
    volumes:
      - ssh-data:/root/.ssh
